apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/hadoop-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
