# Versão corrigida do hadoop-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Explicitamente sem storageClass
  hostPath:
    path: "/mnt/hadoop-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Deve corresponder ao PV (vazio)
  resources:
    requests:
      storage: 30Gi
  volumeName: hadoop-pv  # Referência explícita ao PV