kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 9870  # NameNode UI
    hostPort: 9870
  - containerPort: 8088  # ResourceManager UI
    hostPort: 8088
  extraMounts:
  - hostPath: /mnt/hadoop-data
    containerPath: /mnt/hadoop-data
- role: worker
  extraMounts:
  - hostPath: /mnt/hadoop-data
    containerPath: /mnt/hadoop-data
- role: worker
  extraMounts:
  - hostPath: /mnt/hadoop-data
    containerPath: /mnt/hadoop-data