apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: namenode
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-hdfs
        image: my-hadoop-namenode:3.3.6
        command:
        - "/bin/bash"
        - "-c"
        - |
          mkdir -p /hadoop-data/namenode
          chown -R 1000:1000 /hadoop-data
          if [ ! -f /hadoop-data/namenode/VERSION ]; then
            echo "Formatting namenode..."
            hdfs namenode -format -force -nonInteractive 2>&1 | tee /hadoop-data/namenode/format.log
            touch /hadoop-data/namenode/formatted
          fi
        env:
        - name: HDFS_CONF_dfs_namenode_name_dir
          value: /hadoop-data/namenode
        volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop-data
      - name: init-config
        image: my-hadoop-namenode:3.3.6
        command:
        - "/bin/bash"
        - "-c"
        - |
          mkdir -p /writable-conf
          cp -r /etc/hadoop/* /writable-conf/
          chmod -R 755 /writable-conf
          sleep 5 # Adiciona um pequeno delay
        volumeMounts:
        - name: hadoop-config
          mountPath: /etc/hadoop
          readOnly: true
        - name: writable-conf
          mountPath: /writable-conf
      containers:
      - name: namenode
        image: my-hadoop-namenode:3.3.6
        env:
        - name: HADOOP_CONF_DIR
          value: /writable-conf
        - name: HDFS_NAMENODE_USER
          value: "root"
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:9000
        - name: HDFS_CONF_dfs_replication
          value: "2"
        - name: HDFS_CONF_dfs_namenode_name_dir
          value: /hadoop-data/namenode
        - name: HDFS_CONF_dfs_cluster_name
          value: NeurallakeHDFS
        ports:
        - containerPort: 9000
          name: rpc
        - containerPort: 9870
          name: web
        livenessProbe:
          exec:
            command:
            - hdfs
            - dfsadmin
            - -report
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - name: writable-conf
          mountPath: /writable-conf
        - name: hadoop-data
          mountPath: /hadoop-data
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-config
      - name: writable-conf
        emptyDir: {}
      - name: hadoop-data
        hostPath:
          path: /mnt/hadoop-data
          type: DirectoryOrCreate