apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      containers:
      - name: resourcemanager
        image: apache/hadoop:latest
        command: ["yarn", "resourcemanager"]
        env:
        - name: HADOOP_CONF_DIR
          value: /etc/hadoop
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
spec:
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: resourcemanager
