apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
spec:
  selector:
    matchLabels:
      app: datanode
  replicas: 2
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: hadoop-alpine:3.3.6
        command: ["hdfs", "datanode"]
        env:
        - name: HADOOP_USER_NAME
          value: root
        - name: HDFS_DATANODE_USER
          value: "root"
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:9000
        volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop-data
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-config
      - name: hadoop-data
        persistentVolumeClaim:
          claimName: hadoop-data-pvc
