apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
spec:
  storageClassName: hadoop-storage  # Deve corresponder ao StorageClass do PV manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Deve ser ≤ capacidade do PV (10Gi)
  volumeName: namenode-pv  # Força o uso do PV específico