apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
  - name: rpc
    port: 9000
    targetPort: 9000
  - name: webui
    port: 9870
    targetPort: 9870
