apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
spec:
  storageClassName: hadoop-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hadoop-data"
    type: DirectoryOrCreate