apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  selector:
    matchLabels:
      app: namenode
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: namenode
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: hadoop-sa
      initContainers:
      - name: init-hdfs
        image: hadoop-alpine:3.3.6
        securityContext:
          runAsUser: 0  # Executa como root temporariamente
          privileged: true
        command:
        - "/bin/sh"
        - "-c"
        - |
          # Configuração inicial
          mkdir -p /hadoop-data/namenode
          chown -R 1000:1000 /hadoop-data
          if [ ! -f /hadoop-data/namenode/formatted ]; then
            echo "Formatting namenode..."
            su-exec hadoop hdfs namenode -format -force -nonInteractive
            touch /hadoop-data/namenode/formatted
          fi
        volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop-data
      containers:
      - name: namenode
        image: hadoop-alpine:3.3.6
        securityContext:
          runAsUser: 1000  # UID do usuário hadoop
          runAsGroup: 1000 # GID do grupo hadoop
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        command: 
        - "/bin/sh"
        - "-c"
        - |
          # Verifica permissões antes de iniciar
          chown -R 1000:1000 /hadoop-data
          exec su-exec hadoop hdfs namenode
        env:
        - name: HADOOP_USER_NAME
          value: hadoop
        - name: HDFS_NAMENODE_USER
          value: "hadoop"
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode:9000
        - name: HDFS_CONF_dfs_replication
          value: "2"
        - name: HDFS_CONF_dfs_namenode_name_dir
          value: "/hadoop-data/namenode"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: HADOOP_LOG_DIR
          value: "/opt/hadoop/logs"
        ports:
        - containerPort: 9000
          name: rpc
        - containerPort: 9870
          name: webui
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "hdfs dfsadmin -safemode get | grep -q 'Safe mode is OFF' || exit 1"
          initialDelaySeconds: 120
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "hdfs dfsadmin -report | grep -q 'Live datanodes' && hdfs dfsadmin -safemode get | grep -q 'Safe mode is OFF'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop-data
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-config
          items:
          - key: core-site.xml
            path: core-site.xml
            mode: 0644
          - key: hdfs-site.xml
            path: hdfs-site.xml
            mode: 0644
      - name: hadoop-data
        persistentVolumeClaim:
          claimName: namenode-pvc