apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
spec:
  storageClassName: hadoop-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/hadoop/namenode  # Path dentro do nรณ do Kind
    type: DirectoryOrCreate